# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - tam-application

on:
  push:
    branches:
      - back-end
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: install dependencies
      run: |
        npm install -g yarn
        yarn install

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tam-application'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_91fb1b2095534756b82da368bb9ebdb1 }}
        package: .
